using CommandsProj;
using System.Reflection;
using System.Reflection.Emit;
using System.Threading;

namespace IoCProj.Adapters
{
    public static class AutoGeneratedAdapterFactory
    {
        private static readonly AssemblyBuilder AssemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(
            new AssemblyName("AutoGeneratedAdapters"),
            AssemblyBuilderAccess.Run);

        private static readonly ModuleBuilder ModuleBuilder = AssemblyBuilder.DefineDynamicModule("AutoGeneratedAdapters");
        private static readonly Dictionary<Type, Type> AdapterTypes = new();
        private static readonly object SyncRoot = new();
        private static int _adapterCounter;

        public static object Create(Type interfaceType, object obj)
        {
            if (!interfaceType.IsInterface)
            {
                throw new ArgumentException("Adapter can be generated only for an interface.", nameof(interfaceType));
            }

            var adapterType = GetOrCreateAdapterType(interfaceType);
            return Activator.CreateInstance(adapterType, obj)!;
        }

        private static Type GetOrCreateAdapterType(Type interfaceType)
        {
            lock (SyncRoot)
            {
                if (AdapterTypes.TryGetValue(interfaceType, out var adapterType))
                {
                    return adapterType;
                }

                adapterType = BuildAdapterType(interfaceType);
                AdapterTypes[interfaceType] = adapterType;
                return adapterType;
            }
        }

        private static Type BuildAdapterType(Type interfaceType)
        {
            var typeName = $"AutoGenerated.{SanitizeTypeName(interfaceType)}Adapter{Interlocked.Increment(ref _adapterCounter)}";
            var typeBuilder = ModuleBuilder.DefineType(
                typeName,
                TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.Sealed);

            typeBuilder.AddInterfaceImplementation(interfaceType);

            var objField = typeBuilder.DefineField("_obj", typeof(object), FieldAttributes.Private | FieldAttributes.InitOnly);
            DefineConstructor(typeBuilder, objField);

            foreach (var method in interfaceType.GetMethods())
            {
                if (method.IsGenericMethod || method.GetParameters().Any(parameter => parameter.ParameterType.IsByRef))
                {
                    throw new NotSupportedException($"Method '{method.Name}' cannot be adapted.");
                }

                DefineMethod(typeBuilder, interfaceType, objField, method);
            }

            return typeBuilder.CreateType()!;
        }

        private static void DefineConstructor(TypeBuilder typeBuilder, FieldBuilder objField)
        {
            var constructor = typeBuilder.DefineConstructor(
                MethodAttributes.Public,
                CallingConventions.Standard,
                new[] { typeof(object) });

            var il = constructor.GetILGenerator();
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Call, typeof(object).GetConstructor(Type.EmptyTypes)!);
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldarg_1);
            il.Emit(OpCodes.Stfld, objField);
            il.Emit(OpCodes.Ret);
        }

        private static void DefineMethod(
            TypeBuilder typeBuilder,
            Type interfaceType,
            FieldBuilder objField,
            MethodInfo interfaceMethod)
        {
            var parameters = interfaceMethod.GetParameters();
            var parameterTypes = parameters.Select(parameter => parameter.ParameterType).ToArray();
            var methodBuilder = typeBuilder.DefineMethod(
                interfaceMethod.Name,
                MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.Final | MethodAttributes.HideBySig | MethodAttributes.NewSlot,
                interfaceMethod.ReturnType,
                parameterTypes);

            for (var i = 0; i < parameters.Length; i++)
            {
                methodBuilder.DefineParameter(i + 1, parameters[i].Attributes, parameters[i].Name);
            }

            var il = methodBuilder.GetILGenerator();
            var key = BuildDependencyKey(interfaceType, interfaceMethod);

            if (interfaceMethod.ReturnType == typeof(void))
            {
                EmitResolveCall(il, objField, key, parameters, typeof(ICommand));
                il.Emit(OpCodes.Callvirt, typeof(ICommand).GetMethod(nameof(ICommand.Execute))!);
                il.Emit(OpCodes.Ret);
            }
            else
            {
                EmitResolveCall(il, objField, key, parameters, interfaceMethod.ReturnType);
                il.Emit(OpCodes.Ret);
            }

            typeBuilder.DefineMethodOverride(methodBuilder, interfaceMethod);
        }

        private static void EmitResolveCall(
            ILGenerator il,
            FieldBuilder objField,
            string key,
            ParameterInfo[] parameters,
            Type returnType)
        {
            il.Emit(OpCodes.Ldstr, key);
            il.Emit(OpCodes.Ldc_I4, parameters.Length + 1);
            il.Emit(OpCodes.Newarr, typeof(object));

            il.Emit(OpCodes.Dup);
            il.Emit(OpCodes.Ldc_I4_0);
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldfld, objField);
            il.Emit(OpCodes.Stelem_Ref);

            for (var i = 0; i < parameters.Length; i++)
            {
                il.Emit(OpCodes.Dup);
                il.Emit(OpCodes.Ldc_I4, i + 1);
                il.Emit(OpCodes.Ldarg, i + 1);

                if (parameters[i].ParameterType.IsValueType)
                {
                    il.Emit(OpCodes.Box, parameters[i].ParameterType);
                }

                il.Emit(OpCodes.Stelem_Ref);
            }

            var resolveMethod = typeof(IoC)
                .GetMethod(nameof(IoC.Resolve), BindingFlags.Public | BindingFlags.Static)!
                .MakeGenericMethod(returnType);

            il.Emit(OpCodes.Call, resolveMethod);
        }

        private static string BuildDependencyKey(Type interfaceType, MethodInfo method)
        {
            var methodName = method.Name;
            var parameters = method.GetParameters();

            if (IsGetter(methodName, method.ReturnType, parameters))
            {
                return $"{interfaceType.FullName}:{NormalizeMemberName(methodName[3..])}.get";
            }

            if (IsSetter(methodName, method.ReturnType, parameters))
            {
                return $"{interfaceType.FullName}:{NormalizeMemberName(methodName[3..])}.set";
            }

            return $"{interfaceType.FullName}:{NormalizeMemberName(methodName)}";
        }

        private static bool IsGetter(string methodName, Type returnType, ParameterInfo[] parameters) =>
            methodName.StartsWith("get", StringComparison.OrdinalIgnoreCase)
            && parameters.Length == 0
            && returnType != typeof(void)
            && methodName.Length > 3;

        private static bool IsSetter(string methodName, Type returnType, ParameterInfo[] parameters) =>
            methodName.StartsWith("set", StringComparison.OrdinalIgnoreCase)
            && parameters.Length == 1
            && returnType == typeof(void)
            && methodName.Length > 3;

        private static string NormalizeMemberName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return name;
            }

            return char.ToLowerInvariant(name[0]) + name[1..];
        }

        private static string SanitizeTypeName(Type type)
        {
            var sourceName = type.FullName ?? type.Name;
            var chars = sourceName.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray();
            return new string(chars);
        }
    }
}
