using CommandsProj;
using IoCProj;
using ModelsProj.Classes;

namespace Tests
{
    public interface ITestMovable
    {
        Point GetPosition();
        void SetPosition(Point newValue);
        Vector GetVelocity();
        void Finish();
        Vector ChangeVelocity(Vector newValue);
    }

    internal class TestCommand : ICommand
    {
        private readonly Action _action;

        public TestCommand(Action action)
        {
            _action = action;
        }

        public void Execute()
        {
            _action();
        }
    }

    public class AutoGeneratedAdapterTest
    {
        [Test]
        public void CreateAdapterAndGetValuesTest()
        {
            var obj = new object();
            var position = new Point(12, 5);
            var velocity = new Vector(-7, 3);

            IoC.Resolve<ICommand>("IoC.Register", $"{typeof(ITestMovable).FullName}:position.get",
                (IoC.DependencyStrategy)(args => position)).Execute();

            IoC.Resolve<ICommand>("IoC.Register", $"{typeof(ITestMovable).FullName}:velocity.get",
                (IoC.DependencyStrategy)(args => velocity)).Execute();

            var adapter = IoC.Resolve<ITestMovable>("Adapter", typeof(ITestMovable), obj);

            Assert.That(adapter.GetPosition(), Is.EqualTo(position));
            Assert.That(adapter.GetVelocity(), Is.EqualTo(velocity));
        }

        [Test]
        public void SetValueTest()
        {
            var obj = new object();
            Point? newPosition = null;

            IoC.Resolve<ICommand>("IoC.Register", $"{typeof(ITestMovable).FullName}:position.set",
                (IoC.DependencyStrategy)(args => new TestCommand(() => newPosition = (Point)args[1]))).Execute();

            var adapter = IoC.Resolve<ITestMovable>("Adapter", typeof(ITestMovable), obj);
            var point = new Point(3, 8);

            adapter.SetPosition(point);

            Assert.That(newPosition, Is.EqualTo(point));
        }

        [Test]
        public void SimpleMethodTest()
        {
            var obj = new object();
            var wasFinished = false;
            var velocity = new Vector(10, 20);

            IoC.Resolve<ICommand>("IoC.Register", $"{typeof(ITestMovable).FullName}:finish",
                (IoC.DependencyStrategy)(args => new TestCommand(() => wasFinished = true))).Execute();

            IoC.Resolve<ICommand>("IoC.Register", $"{typeof(ITestMovable).FullName}:changeVelocity",
                (IoC.DependencyStrategy)(args => args[1])).Execute();

            var adapter = IoC.Resolve<ITestMovable>("Adapter", typeof(ITestMovable), obj);

            adapter.Finish();
            var result = adapter.ChangeVelocity(velocity);

            Assert.That(wasFinished, Is.True);
            Assert.That(result, Is.EqualTo(velocity));
        }
    }
}
