using IoCProj.Adapters;
using IoCProj.Commands;
using System.Collections.Concurrent;

namespace IoCProj
{
    public static class IoC
    {

        public delegate object DependencyStrategy(params object[] args);

        private static readonly AsyncLocal<IDictionary<string, DependencyStrategy>> _currentScope =
            new AsyncLocal<IDictionary<string, DependencyStrategy>>();

        private static readonly ConcurrentDictionary<string, DependencyStrategy> _rootScope = new();

        static IoC()
        {
            _rootScope["IoC.Register"] = (args) => new RegisterCommand((string)args[0], (DependencyStrategy)args[1]);
            _rootScope["Scopes.New"] = (args) => new NewScopeCommand((string)args[0]);
            _rootScope["Scopes.Current"] = (args) => new CurrentScopeCommand((string)args[0]);
            _rootScope["Scopes.Id.root"] = (args) => _rootScope;
            _rootScope["Adapter"] = (args) => AutoGeneratedAdapterFactory.Create((Type)args[0], args[1]);
        }

        public static T Resolve<T>(string key, params object[] args)
        {
            if (key == "IoC.Register" || key == "Scopes.New" || key == "Scopes.Current")
            {
                return (T)_rootScope[key](args);
            }

            if (TryResolveFromNamedScope(key, args, out T scopedResult))
            {
                return scopedResult;
            }

            return ResolveFromStorage<T>(_currentScope.Value, key, args);
        }

        private static bool TryResolveFromNamedScope<T>(string key, object[] args, out T result)
        {
            result = default!;

            if (!key.StartsWith("Scopes.", StringComparison.Ordinal) || key.StartsWith("Scopes.Id.", StringComparison.Ordinal))
            {
                return false;
            }

            var scopeAndDependency = key["Scopes.".Length..];
            var separatorIndex = scopeAndDependency.IndexOf('.');

            if (separatorIndex <= 0 || separatorIndex == scopeAndDependency.Length - 1)
            {
                return false;
            }

            var scopeId = scopeAndDependency[..separatorIndex];
            var dependencyKey = scopeAndDependency[(separatorIndex + 1)..];

            if (!_rootScope.TryGetValue($"Scopes.Id.{scopeId}", out var scopeStrategy))
            {
                throw new KeyNotFoundException($"Scope '{scopeId}' not found.");
            }

            var scope = (IDictionary<string, DependencyStrategy>)scopeStrategy();
            result = ResolveFromStorage<T>(scope, dependencyKey, args);

            return true;
        }

        private static T ResolveFromStorage<T>(IDictionary<string, DependencyStrategy>? storage, string key, object[] args)
        {
            if (storage != null && storage.TryGetValue(key, out var strategy))
            {
                return (T)strategy(args);
            }

            if (_rootScope.TryGetValue(key, out var rootStrategy))
            {
                return (T)rootStrategy(args);
            }

            throw new KeyNotFoundException($"Зависимость '{key}' не найдена.");
        }


        internal static IDictionary<string, DependencyStrategy> GetCurrentStorage()
        {
            return _currentScope.Value ?? _rootScope;
        }

        internal static void SetCurrentScope(IDictionary<string, DependencyStrategy> scope)
        {
            _currentScope.Value = scope;
        }
    }
}
